// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX4oM4e_pzHC_azheygrAYcsuVFF0AaiI',
    appId: '1:945754618812:web:9d735b52904a7da71b49b9',
    messagingSenderId: '945754618812',
    projectId: 'club-app-6e8cb',
    authDomain: 'club-app-6e8cb.firebaseapp.com',
    storageBucket: 'club-app-6e8cb.appspot.com',
    measurementId: 'G-2D4TTV9K8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaSOtCHvboYJFsCEa9AK9UFIPZr66AA3k',
    appId: '1:945754618812:android:282f8df6e7ec25151b49b9',
    messagingSenderId: '945754618812',
    projectId: 'club-app-6e8cb',
    storageBucket: 'club-app-6e8cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr4rmBz2AIEWggklUQ3We83Vr-Ebu5NfU',
    appId: '1:945754618812:ios:3fa2f7d6deaab17a1b49b9',
    messagingSenderId: '945754618812',
    projectId: 'club-app-6e8cb',
    storageBucket: 'club-app-6e8cb.appspot.com',
    iosClientId: '945754618812-p0nf3kmomtobqmfte0d27q51qln6als2.apps.googleusercontent.com',
    iosBundleId: 'com.example.clubApp5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr4rmBz2AIEWggklUQ3We83Vr-Ebu5NfU',
    appId: '1:945754618812:ios:3fa2f7d6deaab17a1b49b9',
    messagingSenderId: '945754618812',
    projectId: 'club-app-6e8cb',
    storageBucket: 'club-app-6e8cb.appspot.com',
    iosClientId: '945754618812-p0nf3kmomtobqmfte0d27q51qln6als2.apps.googleusercontent.com',
    iosBundleId: 'com.example.clubApp5',
  );
}
